steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'VITE_API_BASE_URL=${_VITE_API_BASE_URL}', '-t', 'gcr.io/$PROJECT_ID/outwitters-web', '-f', 'client/Dockerfile', '.']
images:
  - 'gcr.io/$PROJECT_ID/outwitters-web'
substitutions:
  _VITE_API_BASE_URL: ''
